// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go.kirha.ai/mcp-installer/internal/adapters/factories/installer"
	"go.kirha.ai/mcp-installer/internal/applications/installer"
)

// Injectors from wire.go:

func ProvideInstallerApplication() (*installer.Application, error) {
	installerFactory := installerfactory.NewFactory()
	application := installer.New(installerFactory)
	return application, nil
}
